name: Lint and test Cairo
# This workflow runs linting and tests on all pull requests and pushes to the main branch.
# It includes Markdown linting, Cairo formatting checks, running tests with coverage,
# and uploading the coverage report to Codecov.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and test Cairo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        partition: [ 1, 2, 3 ]
    steps:
      - uses: actions/checkout@v6

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.15.0

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v4

      - name: Install starknet-foundry
        run: |
          asdf plugin add starknet-foundry
          asdf install starknet-foundry nightly-2026-01-20
          asdf set starknet-foundry nightly-2026-01-20

      - name: Install cairo-coverage
        run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v16
        with:
          globs: |
            *.md
            !PULL_REQUEST_TEMPLATE.md

      - name: Cairo lint
        run: scarb fmt --check --workspace

      - name: Run tests
        # run: snforge test --partition '${{ matrix.partition }}/3' --workspace --features fuzzing --fuzzer-runs 200
        run: |
          set -o pipefail
          snforge test --partition '${{ matrix.partition }}/3' --workspace --features fuzzing --fuzzer-runs 200
          status=${PIPESTATUS[0]}
          if [ "$status" -ne 0 ]; then
            echo "snforge failed (exit=$status). Last 200 lines:"
            tail -n 200 snforge.log || true
            exit "$status"
          fi


      - name: Run tests and generate coverage report
        run: snforge test --partition '${{ matrix.partition }}/3' --workspace --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
